# Generated by Django 6.1 on 2026-08-11 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidates/profile/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('current_job_title', models.CharField(blank=True, max_length=150)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
